Repository microsoft/hyperspace, pull requests merged in 2020-08, with the labels that each got.

#99 Replace LogicalPlanSerDeUtils
  src/main/scala/com/microsoft/hyperspace/actions/CreateAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/test/scala/com/microsoft/hyperspace/actions/RefreshActionTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCacheTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogManagerImplTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/rankers/JoinIndexRankerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/HyperspaceRuleTestSuite.scala
  src/test/scala/com/microsoft/hyperspace/util/JsonUtilsTests.scala
Labels: breaking changes

#102 e2e tests showing aliases not supported in join rule
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
Labels: intermediate issue

#101 Remove "path" key in DF read options
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala
  src/test/scala/com/microsoft/hyperspace/actions/CreateActionTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
Labels: enhancement

#78 Case Sensitivity: Support Case Insensitive Index Column Names
  src/main/scala/com/microsoft/hyperspace/actions/CreateAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/util/IndexNameUtils.scala
  src/main/scala/com/microsoft/hyperspace/util/ResolverUtils.scala
  src/test/scala/com/microsoft/hyperspace/actions/CreateActionTest.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/FilterIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/JoinIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/util/IndexNameUtilsTests.scala
Labels: enhancement

#100 Guidelines & Template for Design Proposals
  CONTRIBUTING.md
  docs/design/TEMPLATE.md
  docs/design/img/sample.png
  docs/design/img/sample.svg
Labels: documentation, proposal

#36 Python bindings for Hyperspace
  azure-pipelines.yml
  build.sbt
  docs/_docs/01-ug-quick-start-guide.md
  project/plugins.sbt
  python/hyperspace/__init__.py
  python/hyperspace/hyperspace.py
  python/hyperspace/indexconfig.py
  python/hyperspace/testing/__init__.py
  python/hyperspace/testing/utils.py
  python/hyperspace/tests/__init__.py
  python/hyperspace/tests/test_indexmanagement.py
  python/hyperspace/tests/test_indexutilization.py
  python/run-tests.py
  run-tests.py
  script/download_spark.sh
Labels: enhancement

#113 Add .gitignore for Python
  python/.gitignore
Labels: infrastructure

#117 Fix CreateAction test where path comparison fails on Windows
  src/test/scala/com/microsoft/hyperspace/actions/CreateActionTest.scala
Labels: bug

#116 Updating python API doc
  docs/_docs/01-ug-quick-start-guide.md
Labels: documentation

#122 Store file name, size and modified time of index files in metadata
  src/main/scala/com/microsoft/hyperspace/actions/CreateAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogManagerImplTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
Labels: breaking changes, enhancement, intermediate issue

#128 Index metadata should always store absolute paths (alternate solution)
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/util/PathUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/plananalysis/ExplainTest.scala
Labels: enhancement

#121 Add lineage column(s) to index records
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/test/scala/com/microsoft/hyperspace/SampleData.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/HyperspaceSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
Labels: enhancement

#138 Change lineage to save full file path
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
Labels: enhancement
