Repository microsoft/hyperspace, pull requests merged in 2020-09, with the labels that each got.

#139 New Tree based Structure for index metadata
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/plananalysis/PlanAnalyzer.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/util/PathUtils.scala
  src/test/scala/com/microsoft/hyperspace/TestUtils.scala
  src/test/scala/com/microsoft/hyperspace/actions/RefreshActionTest.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCacheTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogManagerImplTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/plananalysis/ExplainTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rankers/JoinIndexRankerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/FilterIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/HyperspaceRuleTestSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/JoinIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
  src/test/scala/com/microsoft/hyperspace/util/JsonUtilsTests.scala
Labels: breaking changes, enhancement

#152 Add HyperspaceConf
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/util/HyperspaceConf.scala
Labels: enhancement

#151 Hybrid scan operator for leveraging index alongside newly appended data - BucketUnion
  src/main/scala/com/microsoft/hyperspace/index/execution/BucketUnionExec.scala
  src/main/scala/com/microsoft/hyperspace/index/execution/BucketUnionStrategy.scala
  src/main/scala/com/microsoft/hyperspace/index/plans/logical/BucketUnion.scala
  src/test/scala/com/microsoft/hyperspace/index/BucketUnionTest.scala
Labels: enhancement

#162 Add merge functionality on Directory object
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
Labels: enhancement

#142 Add support for delete to index refresh
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshDeleteAction.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/telemetry/HyperspaceEvent.scala
  src/main/scala/com/microsoft/hyperspace/util/HyperspaceConf.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
Labels: enhancement

#177 Expose HyperspaceSuite.withTempDir() to be used in tests involving temporary directories.
  src/main/scala/org/apache/spark/util/hyperspace/Utils.scala
  src/test/scala/com/microsoft/hyperspace/index/HyperspaceSuite.scala
Labels: enhancement

#165 Modify logical plan to merge newly appended files and index data
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/execution/BucketUnionExec.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/main/scala/com/microsoft/hyperspace/package.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: advanced issue, enhancement
