Repository microsoft/hyperspace, pull requests merged in 2020-10, with the labels that each got.

#163 Add RefreshIncrementalAction to support index creation on newly appended data
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/telemetry/HyperspaceEvent.scala
  src/main/scala/com/microsoft/hyperspace/util/HyperspaceConf.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/HyperspaceSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
Labels: advanced issue, enhancement

#178 Skip applying rules for modified plans by Hyperspace
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/FilterIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/JoinIndexRuleTest.scala
Labels: intermediate issue

#173 Check indexed and included columns before signature calculation
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: intermediate issue

#188 Add "appended" and "deleted" source files in index metadata
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
Labels: enhancement

#171 Inject push-down filter to exclude indexed rows from deleted files
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/main/scala/com/microsoft/hyperspace/util/HyperspaceConf.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: advanced issue, enhancement

#191 Refresh delete and append should update "deleted" and "appended" files in metadata
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshDeleteAction.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
Labels: bug

#199 Change lineage UDF to fix CreateIndex performance issue
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
Labels: bug

#187 Merge append and delete actions on indexes on modified source data
  src/main/scala/com/microsoft/hyperspace/Hyperspace.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala
  src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala
  src/main/scala/com/microsoft/hyperspace/util/HyperspaceConf.scala
  src/test/scala/com/microsoft/hyperspace/TestUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
Labels: advanced issue, enhancement

#205 Use configs of previous LogEntry for refresh action
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/util/HyperspaceConf.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
Labels: bug

#166 Optimize Index, with "quick" and "full" modes
  src/main/scala/com/microsoft/hyperspace/Hyperspace.scala
  src/main/scala/com/microsoft/hyperspace/actions/Constants.scala
  src/main/scala/com/microsoft/hyperspace/actions/OptimizeAction.scala
  src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala
  src/main/scala/com/microsoft/hyperspace/telemetry/HyperspaceEvent.scala
  src/main/scala/com/microsoft/hyperspace/util/HyperspaceConf.scala
  src/test/scala/com/microsoft/hyperspace/TestUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
Labels: advanced issue, enhancement

#207 Support modified source files for refresh incremental mode
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
Labels: bug, enhancement

#155 [DESIGN DOC]: Hybrid Scan for File/Partition Mutable Datasets
  docs/design/150-hybrid-scan-for-file-partition-mutable-datasets.md
Labels: advanced issue, documentation, proposal

#154 [DESIGN DOC]: Incremental Index Maintenance for File/Partition Mutable Datasets.md
  docs/design/136-incremental-index-maintenance-for-file-partition-mutable-datasets.md
Labels: advanced issue, documentation, proposal

#156 [DESIGN DOC]: Hyperspace for Delta Lake
  docs/design/148-hyperspace-for-delta-lake.md
Labels: advanced issue, documentation, proposal

#209 User document skeleton for mutable dataset
  docs/_docs/03-ug-mutable-dataset.md
Labels: documentation

#213 Test enhancement for handling modified files in incremental refresh
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
Labels: enhancement

#212 Update documentation - Add lineage and optimize configs
  docs/_docs/02-ug-configuration.md
Labels: documentation

#214 Remove duplicates in appendedFiles and deletedFiles
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
Labels: bug

#215 Optimize Hybrid Scan for deleted files
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanTest.scala
Labels: enhancement

#216 Update documentation - Refresh index
  docs/_docs/03-ug-mutable-dataset.md
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
Labels: documentation

#219 Check source data change before full refresh
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala
  src/test/scala/com/microsoft/hyperspace/actions/RefreshActionTest.scala
Labels: enhancement

#221 No operation for non-optimizable index data files in OptimizeIndex
  src/main/scala/com/microsoft/hyperspace/actions/OptimizeAction.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
Labels: enhancement

#228 Store appended files and deleted files as Content type in IndexLogEntry
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshDeleteAction.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/HyperspaceRuleTestSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: breaking changes, enhancement

#232 Merge RefreshAppendAction and RefreshDeleteAction
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/OptimizeAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshDeleteAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshIncrementalAction.scala
  src/main/scala/com/microsoft/hyperspace/index/DataFrameWriterExtensions.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/telemetry/HyperspaceEvent.scala
  src/test/scala/com/microsoft/hyperspace/index/DataFrameWriterExtensionsTests.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
Labels: enhancement

#217 Update documentation - Optimize index
  docs/_docs/03-ug-mutable-dataset.md
  docs/_docs/05-ug-optimize.md
Labels: documentation
