Repository microsoft/hyperspace, pull requests merged in 2020-11, with the labels that each got.

#235 Add Update structure for appended files and deleted files
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: breaking changes

#225 Support Hybrid Scan for partitioned source data
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanForNonPartitionedDataSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanForPartitionedDataSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanTest.scala
Labels: bug

#218 User documentation - Hybrid Scan
  docs/_data/navigation.yml
  docs/_docs/02-ug-configuration.md
  docs/_docs/03-ug-mutable-dataset.md
Labels: documentation

#242 Clean up Hyperspace-related configs
  docs/_docs/02-ug-configuration.md
  docs/_docs/04-ug-faqs.md
  python/hyperspace/testing/utils.py
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/PathResolver.scala
  src/main/scala/com/microsoft/hyperspace/util/HyperspaceConf.scala
  src/test/scala/com/microsoft/hyperspace/HyperspaceConfSuite.scala
Labels: enhancement

#244 Rename IndexLogEntry.extra to IndexLogEntry.properties
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
Labels: breaking changes, enhancement

#223 Introduce IndexLogEntryTag for auxiliary data while applying rules
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntryTags.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: enhancement

#234 Numeric lineage implementation
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/OptimizeAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshIncrementalAction.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/SampleData.scala
  src/test/scala/com/microsoft/hyperspace/TestUtils.scala
  src/test/scala/com/microsoft/hyperspace/actions/RefreshActionTest.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCacheTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogManagerImplTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/rankers/JoinIndexRankerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/HyperspaceRuleTestSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
  src/test/scala/com/microsoft/hyperspace/util/JsonUtilsTests.scala
Labels: enhancement

#259 Update docs to use version 0.3.0
  docs/_docs/01-ug-quick-start-guide.md
  docs/_pages/home.md
Labels: documentation

#268 Sort source file list in FileBasedSignatureProvider
  src/main/scala/com/microsoft/hyperspace/index/FileBasedSignatureProvider.scala
Labels: breaking changes, bug

#267 Fix full path problem in IndexLogEntry
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
Labels: bug

#227 Pluggable source provider
  src/main/scala/com/microsoft/hyperspace/Hyperspace.scala
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/FileBasedSignatureProvider.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/FileBasedSourceProviderManager.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/interfaces.scala
  src/main/scala/com/microsoft/hyperspace/util/CacheWithTransform.scala
  src/main/scala/com/microsoft/hyperspace/util/HyperspaceConf.scala
  src/test/scala/com/microsoft/hyperspace/actions/CreateActionTest.scala
  src/test/scala/com/microsoft/hyperspace/actions/RefreshActionTest.scala
Labels: enhancement
