Repository microsoft/hyperspace, pull requests merged in 2020-12, with the labels that each got.

#278 Fix for incorrect explain behavior when df optimized plan has been materialized
  src/main/scala/com/microsoft/hyperspace/index/plananalysis/PlanAnalyzer.scala
  src/main/scala/org/apache/spark/sql/hyperspace/utils/package.scala
  src/test/scala/com/microsoft/hyperspace/index/plananalysis/ExplainTest.scala
Labels: bug

#238 Support refresh quick mode by using Hybrid Scan
  src/main/scala/com/microsoft/hyperspace/actions/RefreshQuickAction.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/main/scala/com/microsoft/hyperspace/telemetry/HyperspaceEvent.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: enhancement

#296 Fix sample notebooks regarding index and included columns
  notebooks/csharp/Hitchhikers Guide to Hyperspace.ipynb
  notebooks/python/Hitchhikers Guide to Hyperspace.ipynb
  notebooks/scala/Hitchhikers Guide to Hyperspace.ipynb
Labels: documentation
