Repository microsoft/hyperspace, pull requests merged in 2020-07, with the labels that each got.

#80 Fix invalid package name at spark-shell command
  docs/_docs/01-ug-quick-start-guide.md
Labels: documentation

#83 Creating index fails for csv data where data is materialized before index creation
  src/main/scala/com/microsoft/hyperspace/index/serde/LogicalPlanSerDeUtils.scala
  src/main/scala/com/microsoft/hyperspace/index/serde/package.scala
  src/test/scala/com/microsoft/hyperspace/index/LogicalPlanSerDeTests.scala
Labels: bug

#84 Add import statement for IndexConfig in quick-start-guide
  docs/_docs/01-ug-quick-start-guide.md
Labels: documentation

#86 Backward compatibility support for json and csv index creation
  src/main/scala/com/microsoft/hyperspace/index/serde/LogicalPlanSerDeUtils.scala
Labels: enhancement

#88 Replace printStackTrace with Logging
  src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala
Labels: enhancement

#93 Remove duplicate setups in tests
  src/test/scala/com/microsoft/hyperspace/HyperspaceTests.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/HyperspaceSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/plananalysis/ExplainTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/FilterIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/JoinIndexRuleTest.scala
Labels: enhancement

#89 Deduplicate getIndexesForPlan and findCoveringIndexes
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/FilterIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/HyperspaceRuleTestSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/JoinIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleTestHelper.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: enhancement

#73 Change FilterIndex rule to cover select all columns case
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/FilterIndexRuleTest.scala
Labels: bug, enhancement

#87 Support for hyperspace event logging
  src/main/scala/com/microsoft/hyperspace/ActiveSparkSession.scala
  src/main/scala/com/microsoft/hyperspace/actions/Action.scala
  src/main/scala/com/microsoft/hyperspace/actions/CancelAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/CreateAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/DeleteAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RestoreAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/VacuumAction.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/telemetry/Constants.scala
  src/main/scala/com/microsoft/hyperspace/telemetry/HyperspaceEvent.scala
  src/main/scala/com/microsoft/hyperspace/telemetry/HyperspaceEventLogging.scala
  src/test/scala/com/microsoft/hyperspace/actions/ActionTest.scala
Labels: enhancement

#77 Add signature computation support for arbitrary logical plans
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/FileBasedSignatureProvider.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexSignatureProvider.scala
  src/main/scala/com/microsoft/hyperspace/index/LogicalPlanSignatureProvider.scala
  src/main/scala/com/microsoft/hyperspace/index/PlanSignatureProvider.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/FileBasedSignatureProviderTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexSignatureProviderTest.scala
  src/test/scala/com/microsoft/hyperspace/index/SignatureProviderTestUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/HyperspaceRuleTestSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/JoinIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleTestHelper.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: enhancement
