Repository microsoft/hyperspace, pull requests merged in 2021-03, with the labels that each got.

#375 Fix Iceberg lineage for windows
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/iceberg/IcebergRelation.scala
  src/test/scala/com/microsoft/hyperspace/index/HyperspaceSuite.scala
Labels: bug

#384 [Gold Standard]: Initial code for spark only setup with a single query
  src/test/resources/tpcds/spark-2.4/approved-plans-v1_4/q1/explain.txt
  src/test/resources/tpcds/spark-2.4/approved-plans-v1_4/q1/simplified.txt
  src/test/scala/com/microsoft/hyperspace/goldstandard/PlanStabilitySuite.scala
  src/test/scala/com/microsoft/hyperspace/goldstandard/TPCDSBase.scala
Labels: enhancement

#272 Add Delta Lake version history to IndexLogEntry for efficient time travel query
  src/main/scala/com/microsoft/hyperspace/actions/Action.scala
  src/main/scala/com/microsoft/hyperspace/actions/CreateAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/OptimizeAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshIncrementalAction.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/FileBasedSourceProviderManager.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/iceberg/IcebergFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/iceberg/IcebergRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/interfaces.scala
  src/test/scala/com/microsoft/hyperspace/index/DeltaLakeIntegrationTest.scala
Labels: advanced issue, enhancement

#392 Correctly pass HadoopConfiguration to Content.fromDirectory
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/OptimizeAction.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTest.scala
Labels: bug
