Repository microsoft/hyperspace, pull requests merged in 2021-06, with the labels that each got.

#451 Update the JAR name from hyperspace-core_spark*.* to hyperspace-core-spark*.*
  azure-pipelines.yml
  build.sbt
  python/run-tests.py
Labels: infrastructure

#455 Upgrade sbt-pgp to 2.1.2
  project/plugins.sbt
Labels: infrastructure

#459 Fix StructType serialization
  src/main/scala-spark2/com/microsoft/hyperspace/shim/StructTypeConverter.scala
  src/main/scala-spark3/com/microsoft/hyperspace/shim/StructTypeConverter.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/CoveringIndex.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/iceberg/IcebergRelation.scala
  src/main/scala/com/microsoft/hyperspace/util/JsonUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogManagerImplTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/HyperspaceRuleSuite.scala
Labels: breaking changes, enhancement

#464 Fix index cache bug
  src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTest.scala
Labels: bug

#467 Fix ResolverUtils to handle StructType column properly
  src/main/scala/com/microsoft/hyperspace/util/ResolverUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexNestedTest.scala
  src/test/scala/com/microsoft/hyperspace/util/ResolverUtilsTest.scala
Labels: bug

#470 Add windows build pipeline
  azure-pipelines.yml
  ci/linux_test.yml
  ci/windows_test.yml
Labels: infrastructure

#471 Documentation: coding style setting with examples
  README.md
  docs/assets/images/project_structure.png
  docs/assets/images/scalafmt_settings.png
  docs/coding-guidelines/scala-coding-style.md
Labels: documentation

#473 Reformat files with scalafmt
  dev/.scalafmt.conf
  src/main/scala-spark2/com/microsoft/hyperspace/index/sources/iceberg/IcebergShims.scala
  src/main/scala-spark3.0/com/microsoft/hyperspace/index/sources/iceberg/IcebergShims.scala
  src/main/scala-spark3.1/com/microsoft/hyperspace/index/sources/iceberg/IcebergShims.scala
  src/main/scala/com/fasterxml/jackson/hyperspace/module/scala/ScalaObjectMapper.scala
  src/main/scala/com/microsoft/hyperspace/Hyperspace.scala
  src/main/scala/com/microsoft/hyperspace/actions/CancelAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/CreateAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshIncrementalAction.scala
  src/main/scala/com/microsoft/hyperspace/index/CoveringIndex.scala
  src/main/scala/com/microsoft/hyperspace/index/Index.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntryTags.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexStatistics.scala
  src/main/scala/com/microsoft/hyperspace/index/execution/BucketUnionStrategy.scala
  src/main/scala/com/microsoft/hyperspace/index/plananalysis/PlanAnalyzer.scala
  src/main/scala/com/microsoft/hyperspace/index/plans/logical/BucketUnion.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/ApplyHyperspace.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/IndexFilter.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/FileBasedSourceProviderManager.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeRelationMetadata.scala
  src/main/scala/com/microsoft/hyperspace/package.scala
  src/main/scala/com/microsoft/hyperspace/telemetry/HyperspaceEvent.scala
  src/main/scala/com/microsoft/hyperspace/util/ResolverUtils.scala
  src/test/scala/com/microsoft/hyperspace/SampleNestedData.scala
  src/test/scala/com/microsoft/hyperspace/goldstandard/PlanStabilitySuite.scala
  src/test/scala/com/microsoft/hyperspace/goldstandard/TPCDSBase.scala
  src/test/scala/com/microsoft/hyperspace/index/BucketUnionTest.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexNestedTest.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexTest.scala
  src/test/scala/com/microsoft/hyperspace/index/DeltaLakeIntegrationTest.scala
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTest.scala
  src/test/scala/com/microsoft/hyperspace/index/FileIdTrackerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanForNonPartitionedDataTest.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanSuite.scala
  src/test/scala/com/microsoft/hyperspace/index/IcebergIntegrationTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCacheTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexTest.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexNestedTest.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTest.scala
  src/test/scala/com/microsoft/hyperspace/index/ScoreBasedIndexPlanOptimizerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rankers/JoinIndexRankerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/FilterIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/JoinIndexRuleTest.scala
  src/test/scala/com/microsoft/hyperspace/util/JsonUtilsTest.scala
Labels: formatting
