Repository microsoft/hyperspace, pull requests merged in 2021-04, with the labels that each got.

#393 Introduce "ResolvedColumn" to simplify handling resolved columns
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/util/ResolverUtils.scala
  src/main/scala/com/microsoft/hyperspace/util/SchemaUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexNestedTest.scala
  src/test/scala/com/microsoft/hyperspace/index/RefreshIndexNestedTest.scala
  src/test/scala/com/microsoft/hyperspace/util/ResolverUtilsTest.scala
  src/test/scala/com/microsoft/hyperspace/util/SchemaUtilsTest.scala
Labels: enhancement

#367 Add hyperspace version to index log entry metadata
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/HyperspaceRuleSuite.scala
Labels: enhancement

#389 Check available index versions for Delta Lake time travel query
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeRelation.scala
  src/test/scala/com/microsoft/hyperspace/index/DeltaLakeIntegrationTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogManagerImplTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexStatisticsTest.scala
Labels: enhancement

#378 Update CONTRIBUTING.md for PR submission guide for a major feature
  CONTRIBUTING.md
Labels: documentation

#433 Handle empty version string in DeltaLakeRelation.closestIndex
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeRelation.scala
  src/test/scala/com/microsoft/hyperspace/index/DeltaLakeIntegrationTest.scala
Labels: bug

#435 More information on using IntelliJ
  README.md
Labels: documentation

#436 Fix sbt-launch-lib.bash
  build/sbt-launch-lib.bash
Labels: infrastructure
