Repository microsoft/hyperspace, pull requests merged in 2021-02, with the labels that each got.

#348 Update user documentation for quick refresh
  docs/_docs/03-ug-mutable-dataset.md
  docs/_docs/05-ug-optimize.md
Labels: documentation

#329 Add config to use bucketed scan for filter indexes
  src/main/scala/com/microsoft/hyperspace/index/IndexConstants.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/main/scala/com/microsoft/hyperspace/util/HyperspaceConf.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanForDeltaLakeTest.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanForNonPartitionedDataTest.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanSuite.scala
Labels: enhancement

#349 Fix e2e tests on managed tables and enable external table tests.
  build.sbt
  src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTest.scala
Labels: bug, enhancement

#355 Introduce SourceRelation/FileBasedRelation traits to remove direct dependency on LogicalRelation from actions/rules
  src/main/scala/com/microsoft/hyperspace/actions/CreateAction.scala
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala
  src/main/scala/com/microsoft/hyperspace/index/FileBasedSignatureProvider.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexSignatureProvider.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/FileBasedSourceProviderManager.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeRelation.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/interfaces.scala
  src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala
  src/test/scala/com/microsoft/hyperspace/actions/CreateActionTest.scala
  src/test/scala/com/microsoft/hyperspace/actions/RefreshActionTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: enhancement

#358 Support Iceberg table format
  build.sbt
  src/main/scala/com/microsoft/hyperspace/index/sources/iceberg/IcebergFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/iceberg/IcebergRelation.scala
  src/test/scala/com/microsoft/hyperspace/index/HybridScanForIcebergTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IcebergIntegrationTest.scala
Labels: enhancement

#362 Fix for doc of lineagePairs method of IcebergRelation
  src/main/scala/com/microsoft/hyperspace/index/sources/iceberg/IcebergRelation.scala
Labels: enhancement

#364 Add a sbt-buildinfo plugin to generate BuildInfo object
  build.sbt
  project/plugins.sbt
Labels: enhancement, infrastructure
