Repository microsoft/hyperspace, pull requests merged in 2021-01, with the labels that each got.

#286 Obtain Enhanced Index Statistics
  src/main/scala/com/microsoft/hyperspace/Hyperspace.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexStatistics.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexStatisticsTest.scala
Labels: enhancement

#164 Fix rank algorithm for Hybrid Scan
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntryTags.scala
  src/main/scala/com/microsoft/hyperspace/index/rankers/FilterIndexRanker.scala
  src/main/scala/com/microsoft/hyperspace/index/rankers/JoinIndexRanker.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/JoinIndexRule.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/rankers/FilterIndexRankerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rankers/JoinIndexRankerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/HyperspaceRuleTestSuite.scala
Labels: enhancement, intermediate issue

#316 Expose hyperspace.index(indexName) for Python binding.
  python/hyperspace/hyperspace.py
  python/hyperspace/tests/test_indexmanagement.py
Labels: enhancement

#294 Update notebooks - Hybrid Scan and Incremental Refresh
  notebooks/csharp/Hitchhikers Guide to Hyperspace.ipynb
  notebooks/python/Hitchhikers Guide to Hyperspace.ipynb
  notebooks/scala/Hitchhikers Guide to Hyperspace.ipynb
Labels: documentation

#281 Support incremental refresh index with hive-partition columns
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/FileBasedSourceProviderManager.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/interfaces.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTest.scala
Labels: bug

#313 Use Hadoop yarn clock utils for all time based calculations
  src/main/scala/com/microsoft/hyperspace/Hyperspace.scala
  src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCacheFactory.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCacheTest.scala
Labels: enhancement

#326 Speed up HybridScanForDeltaLakeTest
  build.sbt
  src/test/scala/com/microsoft/hyperspace/index/plananalysis/ExplainTest.scala
Labels: enhancement

#325 Remove logical plan serde related code
  src/main/scala/com/microsoft/hyperspace/index/serde/KryoSerDeUtils.scala
  src/main/scala/com/microsoft/hyperspace/index/serde/LogicalPlanSerDeUtils.scala
  src/main/scala/com/microsoft/hyperspace/index/serde/package.scala
  src/test/scala/com/microsoft/hyperspace/index/LogicalPlanSerDeTest.scala
Labels: enhancement

#330 Remove deleted threshold condition for append-only Hybrid Scan
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: bug

#293 Add new IndexLogEntryTag to avoid duplicate calculation in getCandidateIndexes
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntryTags.scala
  src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala
Labels: enhancement

#337 Update azure-pipelines.yml for parallel builds to speed up CI pipeline.
  azure-pipelines.yml
Labels: infrastructure

#336 Fix wrong use of map of Set for summation
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexStatistics.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogEntryTest.scala
Labels: bug

#327 Use Spark shared Hadoop configuration
  src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala
  src/main/scala/com/microsoft/hyperspace/actions/OptimizeAction.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexDataManager.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
  src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala
  src/main/scala/com/microsoft/hyperspace/index/PathResolver.scala
  src/main/scala/com/microsoft/hyperspace/index/factories.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/default/DefaultFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/index/sources/delta/DeltaLakeFileBasedSource.scala
  src/main/scala/com/microsoft/hyperspace/util/FileUtils.scala
  src/main/scala/com/microsoft/hyperspace/util/PathUtils.scala
  src/test/scala/com/microsoft/hyperspace/index/CreateIndexTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexLogManagerImplTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexManagerTest.scala
  src/test/scala/com/microsoft/hyperspace/index/IndexStatisticsTest.scala
Labels: enhancement

#340 Use Issues for Writing Design Proposals & Move Away from Design Proposal PRs
  .github/ISSUE_TEMPLATE/design-template.md
  CONTRIBUTING.md
  docs/design/136-incremental-index-maintenance-for-file-partition-mutable-datasets.md
  docs/design/148-hyperspace-for-delta-lake.md
  docs/design/150-hybrid-scan-for-file-partition-mutable-datasets.md
  docs/design/TEMPLATE.md
  docs/design/img/sample.png
  docs/design/img/sample.svg
Labels: documentation

#339 Update user documentation for Hybrid Scan threshold configs
  docs/_docs/02-ug-configuration.md
  docs/_docs/03-ug-mutable-dataset.md
  notebooks/csharp/Hitchhikers Guide to Hyperspace.ipynb
  notebooks/python/Hitchhikers Guide to Hyperspace.ipynb
  notebooks/scala/Hitchhikers Guide to Hyperspace.ipynb
Labels: documentation

#343 Update user documentation for Delta Lake
  docs/_data/navigation.yml
  docs/_docs/08-ug-supported-data-formats.md
Labels: documentation

#344 Update home.md to reflect the 0.4.0 release
  docs/_pages/home.md
Labels: documentation

#346 Update developer list in build.sbt
  build.sbt
Labels: documentation
